apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-b-binding
  namespace: tenant-b
subjects:
- kind: User
  name: tenant-b-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: tenant-b-admin
  apiGroup: rbac.authorization.k8s.io
