apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tenant-b-data
  namespace: tenant-b
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
