apiVersion: v1
kind: ResourceQuota
metadata:
  name: user11-quota
  namespace: user11
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"
    pods: "10"
