apiVersion: v1
kind: ResourceQuota
metadata:
  name: user66-quota
  namespace: user66
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    pods: "20"
