apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: user66
spec:
  selector:
    name: nginx-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
